spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.18.175:3306/test-db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: test-user
    password: 123456
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 12346
    connect-timeout: 3s
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

